-- Active: 1679237081569@@127.0.0.1@3306

-- TABELA DE COMPETIÇÕES
CREATE TABLE IF NOT EXISTS
Competitions (
  id VARCHAR(64) PRIMARY KEY UNIQUE NOT NULL,
  name VARCHAR(64) NOT NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
  modality TEXT NOT NULL,
  finished BOOLEAN DEFAULT false
);
-- TABELA DE RESULTADOS
CREATE TABLE IF NOT EXISTS
Results (
  id VARCHAR(64) PRIMARY KEY NOT NULL,
  athlete VARCHAR(64) NOT NULL,
  value REAL,
  unit TEXT,
  competition_id VARCHAR(64) NOT NULL,
  FOREIGN KEY (competition_id) REFERENCES Competitions(id)
);

