-- Active: 1690565897507@@35.226.146.116@3306

DROP TABLE IF EXISTS `Results`;
DROP TABLE IF EXISTS `Competitions`;
DROP TABLE IF EXISTS `Athletes`;

-- TABELA DE COMPETIÇÕES
CREATE TABLE IF NOT EXISTS
Competitions (
  id VARCHAR(64) PRIMARY KEY UNIQUE NOT NULL,
  name VARCHAR(64) NOT NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
  modality VARCHAR(64) NOT NULL,
  finished BOOLEAN DEFAULT false
);

-- TABELA DE ATLETAS

CREATE TABLE IF NOT EXISTS
Athletes (
id VARCHAR (64) PRIMARY KEY NOT NULL,
name VARCHAR(64) NOT NULL
);

-- TABELA DE RESULTADOS
CREATE TABLE IF NOT EXISTS
Results (
  id VARCHAR(64) PRIMARY KEY NOT NULL,
  athlete_id VARCHAR(64) NOT NULL,
  FOREIGN KEY (athlete_id) REFERENCES Athletes(id),
  value REAL,
  unit TEXT,
  competition_id VARCHAR(64) NOT NULL,
  FOREIGN KEY (competition_id) REFERENCES Competitions(id)
);



