POST http://localhost:3300/cemrasos/create
Content-Type: application/json

{
    "competicao" : "100m Rasos",
    "atleta" : "cleto",
    "value" : 7.00,
    "unidade": "s"

    
}
###
POST http://localhost:3003/dardos/create
Content-Type: application/json

{
    "competicao" : "DARDOS",
    "atleta" : "Mauricio",
    "value" : "30",
    "unidade": "m"

    
}
###
GET  http://localhost:3003/cemrasos/all/cem
content-type: application/json
###

GET  http://localhost:3003/cemrasos/all/ranking
content-type: application/json