source 'https://rubygems.org'

git_source(:github) do |repo_name|
  repo_name = "#{repo_name}/#{repo_name}" unless repo_name.include?('/')
  "https://github.com/#{repo_name}.git"
end

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
# gem 'rails', '~> 5.0.2'
gem 'activemodel', '~> 5.0.2'
gem 'activesupport', '~> 5.0.2'
gem 'activerecord', '~> 5.0.2'
gem 'railties', '~> 5.0.2'
gem 'sqlite3'
gem 'active_model_serializers'

# Use Puma as the app server
gem 'puma', '~> 3.0'

# Use Capistrano for deployment
# gem 'capistrano-rails', group: :development

# Use Rack CORS for handling Cross-Origin Resource Sharing (CORS)
# gem 'rack-cors'
group :development, :test do
  gem 'byebug', platform: :mri
  gem 'rspec-rails', '~> 3.5'
end

gem 'simplecov', :require => false, :group => :test

group :development do
  gem 'listen', '~> 3.0.5'
  gem 'rubocop', '~>0.46.0', require: false
  # Spring speeds up development by keeping your application running in
  # the background. Read more: https://github.com/rails/spring
  gem 'spring'
  gem 'spring-watcher-listen', '~> 2.0.0'
end

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]
